export const METAMASK_UPDATED = "METAMASK_UPDATED";

export const TRANSACTION_SUBMITTED = "TRANSACTION_SUBMITTED";
export const CLOSE_TRANSACTION_MODAL = "CLOSE_TRANSACTION_MODAL";

export const CHANGE_NETWORK_MODAL = "CHANGE_NETWORK_MODAL";